### ISSUE TITLE
运行项目的时候报错 

### ISSUE THREAD

**Issue by we125182** [qq83387856/angular2-demo#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-study-demo@1.0.0~prestart: angular-study-demo@1.0.0
6 silly lifecycle angular-study-demo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-study-demo@1.0.0~start: angular-study-demo@1.0.0
8 verbose lifecycle angular-study-demo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-study-demo@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\project\github\angular2-demo\node_modules.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Java\jdk1.7.0_09\bin;C:\Program Files\Java\jdk1.7.0_09\jre\bin;D:\Tomcat\apache-tomcat-7.0.62\lib;D:\Tomcat\apache-tomcat-7.0.62\bin;D:\maven\apache-maven-3.1.1\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\PHP;D:\phabricator\arcanist\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git;C:\Program Files\Git\cmd;C:\Program Files (x86)\Calibre2\;C:\Program Files\nodejs\node_global;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle angular-study-demo@1.0.0~start: CWD: D:\project\github\angular2-demo
11 silly lifecycle angular-study-demo@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --progress --color' ]
12 silly lifecycle angular-study-demo@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular-study-demo@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-study-demo@1.0.0 start: `webpack-dev-server --progress --color`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular-study-demo@1.0.0
16 verbose cwd D:\project\github\angular2-demo
17 error Windows_NT 10.0.14393
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error angular-study-demo@1.0.0 start: `webpack-dev-server --progress --color`
22 error Exit status 1
23 error Failed at the angular-study-demo@1.0.0 start script 'webpack-dev-server --progress --color'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-study-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --progress --color
23 error You can get their info via:
23 error     npm owner ls angular-study-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by houko** [comment]
npm和node请更到最新。
